<<<<<<< HEAD
const PORT = 6565;

const MESSAGE_TYPES = 
=======
const MESSAGE_TYPES =
>>>>>>> b1c0c61cf3fb70af133f013597719c62344f843d
{
    CLIENT: {
        JOIN_WAITING_LIST: "JOIN_WAITING_LIST",
        LEAVE_WAITING_LIST: "LEAVE_WAITING_LIST",
        LEAVE_ROOM: "LEAVE_ROOM",
        AUTHENTICATION: "AUTHENTICATION" // currently only for admin auth
    },
    SERVER: {
        JOIN_ROOM_SUCCESS: "JOIN_ROOM_SUCCESS",
        CLIENT_LEFT: "CLIENT_LEFT",
        IMAGE_STREAM: "IMAGE_STREAM",
        AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
        ADMIN_DASHBOARD: "ADMIN_DASHBOARD",
    },
    ADMIN: {
        
        GET_STATS: "GET_STATS"
    },
    CHAT_MESSAGE: "CHAT_MESSAGE",

};

const MESSAGE_DATA_TYPES = {
    TEXT: "TEXT",
    IMAGE: "IMAGE", // only used by chatLogger
    STATS: "STATS", // only used by admin dashboard
    IMAGE_STREAM_HEADER: "IMAGE_STREAM_HEADER",
    IMAGE_STREAM_CHUNK: "IMAGE_STREAM_CHUNK",
    IMAGE_STREAM_END: "IMAGE_STREAM_END",

};

const ERROR_TYPES = {
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    IMAGE_SIZE_LIMIT_EXCEEDED: "IMAGE_SIZE_LIMIT_EXCEEDED"
};

export { MESSAGE_TYPES, MESSAGE_DATA_TYPES, ERROR_TYPES };